CREATE TABLE IF NOT EXISTS filmsBase(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name VARCHAR(40),
    description VARCHAR(40),
    release_date DATE,
    duration INTEGER,
    likes INTEGER ARRAY
);
CREATE TABLE IF NOT EXISTS usersBase(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(40),
    login VARCHAR(40),
    name VARCHAR(40),
    birthday date,
    friendsids INTEGER ARRAY
);