CREATE TABLE IF NOT EXISTS filmsBase(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name VARCHAR(40),
    description VARCHAR(40),
    release_date DATE,
    duration INTEGER,
    mpa_id int
);
CREATE TABLE IF NOT EXISTS usersBase(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(40),
    login VARCHAR(40),
    name VARCHAR(40),
    birthday date
);
CREATE TABLE IF NOT EXISTS friends(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id INTEGER,
    friend_id INTEGER
);
CREATE TABLE IF NOT EXISTS likes(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id INTEGER,
    film_id INTEGER
);
CREATE TABLE IF NOT EXISTS mpa(
    mpa_id int not null primary key auto_increment,
    name varchar(40) not null,
    constraint MPA_PK primary key (mpa_id)
);
CREATE TABLE IF NOT EXISTS genre(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    genre_id int not null,
    name varchar(255) not null,
    film_id integer
);
CREATE TABLE IF NOT EXISTS genreBase(
    genre_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name varchar(255) not null
);
MERGE INTO mpa
    (mpa_id, name)
    KEY(mpa_id)
    VALUES (1, 'G'),
           (2, 'PG'),
           (3, 'PG-13'),
           (4, 'R'),
           (5, 'NC-17');
MERGE INTO genreBase
    (genre_id, name)
    KEY(genre_id)
    VALUES (1, 'Комедия'),
           (2, 'Драма'),
           (3, 'Мультфильм'),
           (4, 'Триллер'),
           (5, 'Документальный'),
           (6, 'Боевик');
